### PR TITLE
Fix unknown vignette titles in pkgdown site

### LINKED ISSUE #113: Articles have unknown title
The Articles dropdown on the [documentation site](https://ropensci.github.io/crul/) shows "UNKNOWN TITLE" as the title of each article. The `.Rmd` files all lack YAML headers, adding YAML `title` might fix this.

### PR DESCRIPTION
**Pull request by amoeba**
## Description

Fix unknown vignette titles in pkgdown site, as per #113.

Note, I kept the same pkgdown version as you what was used to build the docs on master. I re-documented and re-checked the package just to make sure I didn't break anything and I verified I didn't break your vignette ordering by moving those directives into the YAML headers.

## Related Issue

Closes #113

### CODE REVIEW

**Comment by sckott** [comment]
thanks @amoeba 

can you remove the now redundant vignette titles, e.g., 

```r
crul workflows
==============
```

as now titles are shown twice

**Comment by amoeba** [comment]
Whoops, of course that would happen. Changed and rebuilt.

**Comment by amoeba** [comment]
Found two issues, since fixed:

- RMarkdown vignettes need double quotes around the `title` field. Otherwise, the vignettes don't have top level headers
- I found a broken link from the howto vignette to the async vignette which I thought I'd fix here

**Comment by sckott** [comment]
thanks, LGTM

**Pull request merged**
